In [118]:
import numpy as np

In [119]:
python_list = [1, 2, 3, 4, 5]
python_list

[1, 2, 3, 4, 5]

In [120]:
numpy_array = np.array([1, 2, 3, 4, 5])
print(numpy_array)
print(type(numpy_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [121]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [122]:
multidimensional_array = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(multidimensional_array)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [123]:
#with default values
default_array = np.zeros((2, 3))
default_array1 = np.zeros(2)
print(default_array1)
print(default_array)

[0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [124]:
ones_array = np.ones((2, 3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [125]:
full_array = np.full((2, 3), 4)
print(full_array)

[[4 4 4]
 [4 4 4]]


In [126]:
arrange_array = np.arange(10)
arrange_array1 = np.arange(2, 10, 2)
print(arrange_array)
print(arrange_array1)


[0 1 2 3 4 5 6 7 8 9]
[2 4 6 8]


In [127]:
identity_array = np.eye(3)
identity_array1 = np.eye(3, 5, k=0)
identity_array2 = np.eye(4, dtype=int)
identity_array3 = np.eye(2,4, k=1)
print(identity_array)
print(identity_array1)
print(identity_array2)
print(identity_array3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [128]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_2d


array([[1, 2, 3],
       [4, 5, 6]])

In [129]:
array_2d.shape

(2, 3)

In [130]:
size_of_array = np.array([[10,20,30],[40,50,60]])
size_of_array.size

6

In [131]:
size_of_array.ndim #defines the 1d,2d

2

In [132]:
size_of_array.dtype

dtype('int64')

In [133]:
float_arr = size_of_array.astype(float)
float_arr

array([[10., 20., 30.],
       [40., 50., 60.]])

In [134]:
float_arr.dtype

dtype('float64')

In [135]:
math_operations = np.array([10,20,30])

In [136]:
add = math_operations + 5

In [137]:
mul = math_operations * 4

In [138]:
arr1 = np.array([10,20,30,40,50])

In [139]:
np.sum(arr1)

np.int64(150)

In [140]:
np.mean(arr1)

np.float64(30.0)

In [141]:
np.mean(arr1)


np.float64(30.0)

In [142]:
np.min(arr1)

np.int64(10)

In [143]:
np.max(arr1)

np.int64(50)

In [144]:
np.std(arr1)

np.float64(14.142135623730951)

In [145]:
np.var(arr1)

np.float64(200.0)

In [146]:
indexing = np.array([10,20,30,40,50])
indexing[0]

np.int64(10)

In [147]:
indexing[-1]

np.int64(50)

In [148]:
slicing = np.array([10,20,30,40,50])

In [149]:
slicing[1:4]

array([20, 30, 40])

In [150]:
slicing[1:4:2]

array([20, 40])

In [151]:
slicing[:4]


array([10, 20, 30, 40])

In [152]:
slicing[::2]

array([10, 30, 50])

In [153]:
slicing[::-1]#reversing of array

array([50, 40, 30, 20, 10])

In [154]:
slicing[:-1:2]

array([10, 30])

In [155]:
fancy = np.array([10,20,30,40,50])

In [156]:
fancy[[0,2,3]] #this is another type of indexing

array([10, 30, 40])

In [157]:
fancy[fancy>20]

array([30, 40, 50])

In [158]:
reshaping = np.array([2,4,6,8,10,12])

In [159]:
reshape_arr = reshaping.reshape(2,3) #it affects the original array

In [160]:
reshape_arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [161]:
flattening = np.array([[1,2,3],[4,5,6]])
ravel = flattening.ravel() #only view

In [162]:
ravel

array([1, 2, 3, 4, 5, 6])

In [163]:
flatten = flattening.flatten() #copy 

In [164]:
flatten

array([1, 2, 3, 4, 5, 6])

In [165]:
inserting = np.array([10,20,30,40,50])
inserted_arr = np.insert(inserting, 2,100)
inserted_arr

array([ 10,  20, 100,  30,  40,  50])

In [166]:
inserting_2darr = np.array([[1,2],[3,4]])
new_arr_2d = np.insert(inserting_2darr,1,[7,8],axis=0)
new_arr_2dcolumn = np.insert(inserting_2darr,1,[5,6],axis=1)
new_arr_2d

array([[1, 2],
       [7, 8],
       [3, 4]])

In [167]:
new_arr_2dcolumn

array([[1, 5, 2],
       [3, 6, 4]])

In [168]:
new_arr_2dnone = np.insert(inserting_2darr,1,[5,6],axis=None)
new_arr_2dnone

array([1, 5, 6, 2, 3, 4])

In [169]:
append_of_array = np.array([10,20,30])
new_append = np.append(append_of_array, [50,60,70])
new_append

array([10, 20, 30, 50, 60, 70])

In [170]:
concatenate_array = np.array([[10,20,30],[1,2,3]])
concatenate_arraY = np.array([[40,50,60],[4,5,6]])
new_concatenate = np.concatenate((concatenate_array, concatenate_arraY),axis=0)
new_concatenate

array([[10, 20, 30],
       [ 1,  2,  3],
       [40, 50, 60],
       [ 4,  5,  6]])

In [171]:
new_concatenate_column = np.concatenate((concatenate_array, concatenate_arraY),axis=1)
new_concatenate_column

array([[10, 20, 30, 40, 50, 60],
       [ 1,  2,  3,  4,  5,  6]])

In [172]:
new_concatenate_none = np.concatenate((concatenate_array, concatenate_arraY),axis=None)
new_concatenate_none

array([10, 20, 30,  1,  2,  3, 40, 50, 60,  4,  5,  6])

In [173]:
deleting = np.array([10,20,30])
new_deleted = np.delete(deleting,0)
new_deleted

array([20, 30])

In [174]:
deleting_2darray = np.array([[10,20,30],[40,50,60]])
new_deleted = np.delete(deleting_2darray, 1, axis=1)
new_deleted

array([[10, 30],
       [40, 60]])

In [175]:

new_deleted_row = np.delete(deleting_2darray, 1, axis=0)
new_deleted_row

array([[10, 20, 30]])

In [176]:
stack_arr1 = np.array([1,2,3])
stack_arr2 = np.array([4,5,6])

normal_stack = np.stack((stack_arr1,stack_arr2))
ver_stack = np.vstack(((stack_arr1,stack_arr2)))
hori_stack = np.hstack(((stack_arr1,stack_arr2)))

In [177]:
normal_stack


array([[1, 2, 3],
       [4, 5, 6]])

In [178]:
ver_stack


array([[1, 2, 3],
       [4, 5, 6]])

In [179]:
hori_stack

array([1, 2, 3, 4, 5, 6])

In [180]:
splitting = np.array([10,20,30,40,50,60])
splitted_arr = np.split(splitting,2)

In [181]:
splitted_arr

[array([10, 20, 30]), array([40, 50, 60])]

In [182]:
splitting_2d = np.array([[10,20,30],[40,50,60],[70,80,90]])
splitted_arr_hori = np.hsplit(splitting_2d,3)
splitted_arr_hori

[array([[10],
        [40],
        [70]]),
 array([[20],
        [50],
        [80]]),
 array([[30],
        [60],
        [90]])]

In [183]:
splitted_arr_ver = np.vsplit(splitting_2d,3)
splitted_arr_ver

[array([[10, 20, 30]]), array([[40, 50, 60]]), array([[70, 80, 90]])]

In [184]:
prices = np.array([100, 200, 300, 400, 500])
discount = 10

final_pricesd = prices - (prices * discount / 100)
print(final_pricesd)

[ 90. 180. 270. 360. 450.]


In [185]:
arr2 = np.array([100, 200, 300, 400, 500])

result = arr2 * 2
print(result)

[ 200  400  600  800 1000]


In [186]:
#broadcasting example
matrix = np.array([[1, 2,3], [4,5,6]])
vector = np.array([10, 20, 30])
result_matrix_vector = matrix + vector
print(result_matrix_vector) #expands vector to match matrix shape

[[11 22 33]
 [14 25 36]]


In [187]:
#vectorization example
lis1 = [1, 2, 3, 4, 5]
lis2 = [10, 20, 30, 40, 50] 

result = [a + b for a, b in zip(lis1, lis2)] #list comprehension for element-wise addition
print(result)  # Output: [11, 22, 33, 44, 55]

[11, 22, 33, 44, 55]


In [188]:
#list comprehension 
name = ['Alice', 'Bob', 'Charlie']
new_list = [len(n) for n in name]
print(new_list)
#dictionary comprehension
dict_comp = {n: len(n) for n in name}
print(dict_comp)
# Set comprehension
set_comp = {len(n) for n in name}
print(set_comp) 



[5, 3, 7]
{'Alice': 5, 'Bob': 3, 'Charlie': 7}
{3, 5, 7}


In [189]:
arr3 = np.array([1, 2, 3, 4, 5])
arr4 = np.array([10, 20, 30, 40, 50])
print(arr3 + arr4)
print(arr3 - arr4) 
print(arr3 * arr4)
print(arr3 / arr4) 

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


In [190]:
#handling missing values
arr_with_nan = np.array([1, 2, np.nan, 4, 5])
print(np.isnan(arr_with_nan))  # Check for NaN values
print(np.sum(arr_with_nan))  # Sum without NaN values
print(np.nansum(arr_with_nan))  # Sum treating NaN as zero


[False False  True False False]
nan
12.0

nan
12.0


In [191]:
#replcing nan values with a specific value
arr_with_nan1 = np.array([1, 2, np.nan, 4,  5])
cleaned_arr = np.nan_to_num(arr_with_nan1,nan=100)  # Replace NaN with 100
print(cleaned_arr)
#replacing nan values with the mean of the column
mean_value = np.nanmean(arr_with_nan1)  # Calculate the mean of non-NaN values
arr_with_nan1[np.isnan(arr_with_nan1)] = mean_value  # Replace NaN with mean
print(arr_with_nan1)


[  1.   2. 100.   4.   5.]
[1. 2. 3. 4. 5.]


In [211]:
#infinity functions
arr_with_inf = np.array([1, 2, np.inf, 4, 5])
print(np.isinf(arr_with_inf))  # Check for infinite values  
print(np.sum(arr_with_inf))  # Sum without infinite values
print(np.isfinite(arr_with_inf))  # Check for finite values 
# Replace infinite values with a specific value
cleaned_arr_inf = np.nan_to_num(arr_with_inf, posinf=100, neginf=-100)  # Replace inf with 100 and -inf with -100
print(cleaned_arr_inf)

[False False  True False False]
inf
[ True  True False  True  True]
[  1.   2. 100.   4.   5.]


In [215]:
# Example of using np.where for conditional selection
arr5 = np.array([1, 7, 3, 4, 5])
condition = arr5 > 3
print(np.where(condition, 'Greater than 3', 'Less than or equal to 3'))  # Returns 'Greater than 3' or 'Less than or equal to 3' based on condition


['Less than or equal to 3' 'Greater than 3' 'Less than or equal to 3'
 'Greater than 3' 'Greater than 3']


In [193]:
# Example of using np.select for multiple conditions
conditions = [arr5 < 3, arr5 == 3, arr5 > 3]
choices = ['Less than 3', 'Equal to 3', 'Greater than 3']
result = np.select(conditions, choices, default='Unknown')  
print(result)

['Less than 3' 'Less than 3' 'Equal to 3' 'Greater than 3'
 'Greater than 3']


In [194]:
# Example of using np.clip to limit values within a range
arr6 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
clipped_arr = np.clip(arr6, 3, 7)  # Values below   
# 3 are set to 3, and values above 7 are set to 7
print(clipped_arr)

[3 3 3 4 5 6 7 7 7 7]


In [195]:
# Example of using np.unique to find unique elements
arr7 = np.array([1, 2, 2, 3, 4, 4, 5])
unique_elements = np.unique(arr7)  # Find unique elements in the array
print(unique_elements)

[1 2 3 4 5]


In [196]:
# Example of using np.sort to sort an array
arr8 = np.array([5, 2, 8, 1, 4, 3])     
sorted_arr = np.sort(arr8)  # Sort the array in ascending order
print(sorted_arr)

[1 2 3 4 5 8]


In [197]:
# Example of using np.argsort to get indices of sorted elements
arr9 = np.array([5, 2, 8, 1, 4, 3])
sorted_indices = np.argsort(arr9)  # Get indices that would sort the array  
print(sorted_indices)  # Output: [3 1 5 4 0 2] (indices of sorted elements) 

[3 1 5 4 0 2]


In [198]:
# Example of using np.searchsorted to find insertion indices
arr10 = np.array([1, 3, 5, 7, 9])
values_to_insert = np.array([0, 2, 4, 6, 8, 10])
insertion_indices = np.searchsorted(arr10, values_to_insert)  # Find indices to insert values
print(insertion_indices)  # Output: [0 1 2 3 4 5] (indices where values would be inserted to maintain order) 

[0 1 2 3 4 5]


In [199]:
# Example of using np.meshgrid to create a grid of coordinates
x = np.array([1, 2, 3])     
y = np.array([4, 5])
X, Y = np.meshgrid(x, y)  # Create a grid of coordinates    
print("X:\n", X)
print("Y:\n", Y)  # Output: X and Y are 2D arrays representing the grid of coordinates

X:
 [[1 2 3]
 [1 2 3]]
Y:
 [[4 4 4]
 [5 5 5]]


In [200]:
# Example of using np.linalg to perform linear algebra operations   
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])  
# Matrix multiplication
C = np.dot(A, B)  # Matrix multiplication   
print("Matrix C:\n", C)
# Inverse of a matrix   
A_inv = np.linalg.inv(A)  # Inverse of matrix A
print("Inverse of A:\n", A_inv) 
# Determinant of a matrix
det_A = np.linalg.det(A)  # Determinant of matrix A
print("Determinant of A:", det_A)  # Output: -2.0 (determinant of matrix A)
# Eigenvalues and eigenvectors of a matrix
eigenvalues, eigenvectors = np.linalg.eig(A)  # Eigenvalues and eigenvectors of matrix A
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)  # Output: Eigenvalues and eigenvectors of matrix A  


Matrix C:
 [[19 22]
 [43 50]]
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of A: -2.0000000000000004
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [201]:

# Example of using np.random to generate random numbers
random_numbers = np.random.rand(5)  # Generate 5 random numbers between 0 and 1
print("Random Numbers:", random_numbers)


Random Numbers: [0.19871568 0.00552212 0.81546143 0.70685734 0.72900717]


In [202]:
# Example of using np.random.randint to generate random integers
random_integers = np.random.randint(1, 10, size=5)  # Generate 5 random integers between 1 and 10   
print("Random Integers:", random_integers)

Random Integers: [1 5 7 9 7]
 [1 5 7 9 7]


In [203]:
# Example of using np.random.normal to generate random numbers from a normal distribution
normal_random_numbers = np.random.normal(loc=0, scale=1, size=5)  # Generate 5 random numbers from a normal distribution with mean 0 and standard deviation 1
print("Normal Random Numbers:", normal_random_numbers)

Normal Random Numbers: [-0.16820509  1.16476865 -0.24574769 -0.76966777  1.21217234]


In [204]:


# Example of using np.random.choice to randomly select elements from an array
choices = np.array([1, 2, 3, 4, 5])
random_choice = np.random.choice(choices, size=3, replace=True)  # Randomly select 3 elements from choices with replacement
print("Random Choice:", random_choice)
# Example of using np.random.seed to set a random seed for reproducibility
np.random.seed(42)  # Set a random seed for reproducibility 
random_numbers_seeded = np.random.rand(5)  # Generate 5 random numbers with the same seed
print("Random Numbers with Seed:", random_numbers_seeded)   
# Example of using np.random.shuffle to shuffle an array in place
array_to_shuffle = np.array([1, 2, 3, 4, 5])
np.random.shuffle(array_to_shuffle)  # Shuffle the array in place   
print("Shuffled Array:", array_to_shuffle)  # Output: The array is shuffled in place
# Example of using np.random.permutation to randomly permute an array   
permuted_array = np.random.permutation(array_to_shuffle)  # Randomly permute the array
print("Permuted Array:", permuted_array)  # Output: A new array with elements randomly permuted
# Example of using np.random.binomial to generate random numbers from a binomial distribution
n_trials = 10   
p = 0.5
binomial_random_numbers = np.random.binomial(n_trials, p, size=5)  # Generate 5 random numbers from a binomial distribution with n_trials and probability p
print("Binomial Random Numbers:", binomial_random_numbers)  # Output: Random numbers from a binomial distribution
# Example of using np.random.poisson to generate random numbers from a Poisson distribution 
lambda_param = 3
poisson_random_numbers = np.random.poisson(lambda_param, size=5)  # Generate    
# 5 random numbers from a Poisson distribution with parameter lambda_param
print("Poisson Random Numbers:", poisson_random_numbers)  # Output: Random numbers from a Poisson distribution
# Example of using np.random.uniform to generate random numbers from a uniform distribution 
low = 0
high = 10   
uniform_random_numbers = np.random.uniform(low, high, size=5)  # Generate 5 random numbers from a uniform distribution between low and high
print("Uniform Random Numbers:", uniform_random_numbers)  # Output: Random numbers from a uniform
# distribution between low and high
# Example of using np.random.exponential to generate random numbers from an exponential distribution
scale = 1   
exponential_random_numbers = np.random.exponential(scale, size=5)  # Generate 5 random numbers from an exponential distribution with scale parameter scale
print("Exponential Random Numbers:", exponential_random_numbers)  # Output: Random numbers from an exponential distribution
# Example of using np.random.multinomial to generate random numbers from a multinomial distribution     
n_trials_multinomial = 10
probabilities = [0.2, 0.3, 0.5] 
multinomial_random_numbers = np.random.multinomial(n_trials_multinomial, probabilities, size=5)  # Generate 5 random samples from a multinomial distribution
print("Multinomial Random Numbers:\n", multinomial_random_numbers)  # Output:       
# Random samples from a multinomial distribution with specified probabilities   
# Example of using np.random.choice with probabilities
choices_with_probabilities = np.array([1, 2, 3, 4, 5])
probabilities = [0.1, 0.2, 0.3, 0.2, 0.2]  # Probabilities for each choice
random_choice_with_probabilities = np.random.choice(choices_with_probabilities, size=3, replace=True, p=probabilities)  # Randomly select 3 elements with specified probabilities
print("Random Choice with Probabilities:", random_choice_with_probabilities)  # Output: Randomly selected elements with specified probabilities 
# Example of using np.random.rand to generate random numbers in a specific shape
random_array_shape = np.random.rand(2, 3)  # Generate a 2x3 array of random numbers between 0 and 1
print("Random Array with Shape (2, 3):\n", random_array_shape)  
# Example of using np.random.randn to generate random numbers from a standard normal distribution
random_standard_normal = np.random.randn(2, 3)  # Generate a 2x3 array of random numbers from a standard normal distribution (mean=0, std=1)
print("Random Standard Normal Array:\n", random_standard_normal)  # Output: Random numbers from a standard normal distribution  
# Example of using np.random.randint to generate random integers within a range
random_integers_range = np.random.randint(1, 10, size=(2, 3))  # Generate a 2x3 array of random integers between 1 and 10
print("Random Integers Array:\n", random_integers_range)  # Output:
# Random integers within the specified range


Random Choice: [4 3 3]
Random Numbers with Seed: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
Shuffled Array: [2 1 4 5 3]
Permuted Array: [2 1 4 5 3]
Binomial Random Numbers: [3 6 7 0 9]
Poisson Random Numbers: [2 0 2 2 6]
Uniform Random Numbers: [0.13264961 9.42201756 5.63288218 3.85416503 0.15966252]
Exponential Random Numbers: [0.26252625 0.27578705 1.14968514 0.94159997 1.79092928]
Multinomial Random Numbers:
 [[1 3 6]
 [1 4 5]
 [2 2 6]
 [2 1 7]
 [3 2 5]]
Random Choice with Probabilities: [3 5 4]
Random Array with Shape (2, 3):
 [[0.32654077 0.57044397 0.52083426]
 [0.96117202 0.84453385 0.74732011]]
Random Standard Normal Array:
 [[ 2.34074633  1.07098519  0.09641648]
 [ 0.41910211 -0.95302779 -1.0478706 ]]
Random Integers Array:
 [[1 9 7]
 [9 8 1]]


In [205]:
# Example of using np.random.choice with a 2D array as choices
choices_2d = np.array([[1, 2], [3, 4], [5, 6]])
random_choice_2d = np.random.choice(choices_2d.flatten(), size=3 , replace=True)  # Randomly select 3 elements from the flattened 2D array
print("Random Choice from 2D Array:", random_choice_2d)  # Output: Randomly selected elements from the 2D array 
# Example of using np.random.shuffle with a 2D array
array_to_shuffle_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.random.shuffle(array_to_shuffle_2d)  # Shuffle the 2D array in place
print("Shuffled 2D Array:\n", array_to_shuffle_2d)  # Output: The 2D array is shuffled in place
# Example of using np.random.permutation with a 2D array
permuted_array_2d = np.random.permutation(array_to_shuffle_2d)  # Randomly permute the 2D array
print("Permuted 2D Array:\n", permuted_array_2d)  # Output: A new 2D array with elements randomly permuted
# Example of using np.random.binomial with a 2D array
n_trials_binomial = 10  
p_binomial = 0.5
binomial_random_numbers_2d = np.random.binomial(n_trials_binomial, p_binomial, size=(2, 3))  # Generate a 2x3 array of random numbers from a binomial distribution
print("Binomial Random Numbers 2D:\n", binomial_random_numbers_2d)  # Output: Random numbers from a binomial distribution in a 2D array
# Example of using np.random.poisson with a 2D array
lambda_param = 2.5
poisson_random_numbers_2d = np.random.poisson(lambda_param, size=(2, 3))  # Generate a 2x3  array of random numbers from a Poisson distribution
print("Poisson Random Numbers 2D:\n", poisson_random_numbers_2d)    # Output: Random numbers from a Poisson distribution in a 2D array          
# Example of using np.random.uniform with a 2D array
low_uniform = 0 
high_uniform = 10
uniform_random_numbers_2d = np.random.uniform(low_uniform, high_uniform, size=(2 , 3))  # Generate a 2x3 array of random numbers from a uniform distribution
print("Uniform Random Numbers 2D:\n", uniform_random_numbers_2d)    
# Output: Random numbers from a uniform distribution in a 2D array
# Example of using np.random.exponential with a 2D array    
scale_exponential = 1
exponential_random_numbers_2d = np.random.exponential(scale_exponential, size=(2, 3))  # Generate a 2x3 array of random numbers from an exponential distribution
print("Exponential Random Numbers 2D:\n", exponential_random_numbers_2d)  # Output: Random numbers from an exponential distribution in a 2D array
# Example of using np.random.multinomial with a 2D array    
n_trials_multinomial_2d = 10
probabilities_multinomial = [0.2, 0.3, 0.5]
multinomial_random_numbers_2d = np.random.multinomial(n_trials_multinomial_2d, probabilities_multinomial, size=(2, 3))  # Generate a 2x3 array of random samples from a multinomial distribution
print("Multinomial Random Numbers 2D:\n", multinomial_random_numbers_2d)  # Output: Random samples from a multinomial distribution in a 2D array    


Random Choice from 2D Array: [4 3 3]
Shuffled 2D Array:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Permuted 2D Array:
 [[4 5 6]
 [7 8 9]
 [1 2 3]]
Binomial Random Numbers 2D:
 [[6 3 4]
 [3 7 6]]
Poisson Random Numbers 2D:
 [[1 2 3]
 [5 1 1]]
Uniform Random Numbers 2D:
 [[6.36410411 3.14355981 5.08570691]
 [9.07566474 2.49292229 4.10382923]]
Exponential Random Numbers 2D:
 [[1.40874915 0.25980516 0.08010428]
 [0.3421403  0.17580836 2.65495009]]
Multinomial Random Numbers 2D:
 [[[3 3 4]
  [3 4 3]
  [1 5 4]]

 [[2 4 4]
  [4 2 4]
  [1 2 7]]]


In [206]:
# Example of using np.random.rand with a 3D array
random_array_3d = np.random.rand(2, 3, 4)  # Generate a 2x3x4 array of random numbers between 0 and 1
print("Random Array with Shape (2, 3, 4):\n", random_array_3d)
# Example of using np.random.randn with a 3D array  
random_standard_normal_3d = np.random.randn(2, 3, 4)  # Generate a 2x3x4 array of random numbers from a standard normal distribution
print("Random Standard Normal Array 3D:\n", random_standard_normal_3d)  
# Example of using np.random.randint with a 3D array
random_integers_range_3d = np.random.randint(1, 10, size=(2, 3, 4))  # Generate a 2x3x4 array of random integers between 1 and 10
print("Random Integers Array 3D:\n", random_integers_range_3d)  # Output: Random integers within the specified range in a 3D array
# Example of using np.random.choice with a 3D array as choices  
choices_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
random_choice_3d = np.random.choice(choices_3d.flatten(), size=3, replace=True)  # Randomly select 3 elements from the flattened 3D array
print("Random Choice from 3D Array:", random_choice_3d)  # Output: Randomly selected elements from the 3D array
# Example of using np.random.shuffle with a 3D array        
array_to_shuffle_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
np.random.shuffle(array_to_shuffle_3d)  # Shuffle the 3D array in   place
print("Shuffled 3D Array:\n", array_to_shuffle_3d)  
# Output: The 3D array is shuffled in place
# Example of using np.random.permutation with a 3D array    
permuted_array_3d = np.random.permutation(array_to_shuffle_3d)  # Randomly permute the 3D array
print("Permuted 3D Array:\n", permuted_array_3d)  # Output: A new 3D array with elements randomly permuted
# Example of using np.random.binomial with a 3D array   
n_trials_binomial_3d = 10
p_binomial_3d = 0.5     
binomial_random_numbers_3d = np.random.binomial(n_trials_binomial_3d, p_binomial_3d, size=(2, 3, 4))  # Generate a 2x3x4 array of random numbers from a binomial distribution
print("Binomial Random Numbers 3D:\n", binomial_random_numbers_3d)  # Output: Random numbers from a binomial distribution in a 3D array
# Example of using np.random.poisson with a 3D array    
lambda_param_3d = 2.5
poisson_random_numbers_3d = np.random.poisson(lambda_param_3d, size=(2, 3, 4))  # Generate a 2x3x4 array of random numbers from a Poisson distribution
print("Poisson Random Numbers 3D:\n", poisson_random_numbers_3d)  # Output: Random numbers from a Poisson distribution in a 3D array
# Example of using np.random.uniform with a 3D array    
low_uniform_3d = 0
high_uniform_3d = 10    
uniform_random_numbers_3d = np.random.uniform(low_uniform_3d, high_uniform_3d, size=(2, 3, 4))  # Generate a 2x3x4 array of random numbers from a uniform distribution
print("Uniform Random Numbers 3D:\n", uniform_random_numbers_3d)    
# Output: Random numbers from a uniform distribution in a 3D array
# Example of using np.random.exponential with a 3D array    
scale_exponential_3d = 1
exponential_random_numbers_3d = np.random.exponential(scale_exponential_3d, size=(2, 3, 4))  # Generate a 2x3x4 array of random numbers from an exponential distribution
print("Exponential Random Numbers 3D:\n", exponential_random_numbers_3d)  # Output: Random numbers from an exponential distribution in a 3D array
# Example of using np.random.multinomial with a 3D array
n_trials_multinomial_3d = 10
probabilities_multinomial_3d = [0.2, 0.3, 0.5]
multinomial_random_numbers_3d = np.random.multinomial(n_trials_multinomial_3d, probabilities_multinomial_3d, size=(2, 3, 4))  # Generate a 2x3x4 array of random samples from a multinomial distribution
print("Multinomial Random Numbers 3D:\n", multinomial_random_numbers_3d)  # Output: Random samples from a multinomial distribution in a 3D array      
# Example of using np.random.shuffle with a 3D array and axis
array_to_shuffle_3d_axis = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
np.random.shuffle(array_to_shuffle_3d_axis)  # Shuffle the 3D array in place along the first axis
print("Shuffled 3D Array with Axis:\n", array_to_shuffle_3d_axis)  # Output: The 3D array is shuffled in place along the specified axis 
# Example of using np.random.choice with a 3D array and axis
choices_3d_axis = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
random_choice_3d_axis = np.random.choice(choices_3d_axis.flatten(), size=3, replace=True)  # Randomly select 3 elements from the flattened 3D array
print("Random Choice from 3D Array with Axis:", random_choice_3d_axis)  # Output: Randomly selected elements from the 3D array along the specified axis 


Random Array with Shape (2, 3, 4):
 [[[0.42710779 0.81801477 0.86073058 0.00695213]
  [0.5107473  0.417411   0.22210781 0.11986537]
  [0.33761517 0.9429097  0.32320293 0.51879062]]

 [[0.70301896 0.3636296  0.97178208 0.96244729]
  [0.2517823  0.49724851 0.30087831 0.28484049]
  [0.03688695 0.60956433 0.50267902 0.05147875]]]
Random Standard Normal Array 3D:
 [[[ 0.4777541  -0.25902864 -0.57470921 -0.42149822]
  [ 0.33982096 -0.00738015  0.76729684 -1.14979258]
  [-0.77533611  0.77314086 -0.80182784  1.38401572]]

 [[ 1.40520531  1.39232575 -0.88064082  0.07689495]
  [-0.49343248  0.92316261  1.70660495  0.87358942]
  [ 0.00914435 -0.3655393   0.64908673 -1.22287354]]]
Random Integers Array 3D:
 [[[4 9 1 8]
  [7 2 8 1]
  [9 9 2 7]]

 [[3 7 9 4]
  [1 2 1 5]
  [5 7 9 9]]]
Random Choice from 3D Array: [3 3 8]
Shuffled 3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Permuted 3D Array:
 [[[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]
Binomial Random Numbers 3D:
 [